### ISSUE TITLE
Run evaluation on PP4AV with same approach as evaluation results in the paper

### ISSUE THREAD

**Issue by Zeleni9** [khaclinh/pp4av#2]
Hi, 

I have read the research paper, and evaluated license & face model on PP4AV dataset and didn't get matching results, AP/AR for face models not even close to 40%. I was using https://github.com/rafaelpadilla/review_object_detection_metrics for the evaluation. 

I did not find a way to evaluate custom model using your filtering approach for smaller bounding boxes. Is there a script that is usable to run against PP4AV GT detections in format (YOLO or COCO) and get results AP/AR in the same way you have shown in the research paper to produce results that can be compared. 

Thank you for research and creating the first step towards a good benchmarking dataset for anonymization in the traffic environment.

**Comment by khaclinh** [comment]
Thanks @Zeleni9 for your interesting.
You can find the script to filter smaller bboxes here:
https://github.com/khaclinh/pp4av/blob/main/tools/data_processing/filter_box_threshold.py
In script will work with YOLO data format.

In this repo, you can find several scripts for evaluation. We provide the script to evaluate performance with COCO format:
https://github.com/khaclinh/pp4av/blob/main/evaluations/baseline_evals/main.py
If your model predicted results in YOLO format, we provide script to convert it into COCO format for evaluation:
https://github.com/khaclinh/pp4av/blob/main/tools/data_processing/format_transform.py

Finally, we also provide script (in Matlab) to generate PR curves as WIDER-FACE format. 
![image](https://user-images.githubusercontent.com/6778522/236365372-ead3a8de-d9d9-4b2b-a0d4-5cfa6628f9ef.png)

You can find how to organize the ground truth and prediction make compute it here:
https://github.com/khaclinh/pp4av/tree/main/evaluations/widerface_evals

I hope these guide could be useful to you.
If you have any error or issue while executing script, please feel free to share it with me.
Thanks and best,

**Comment by khaclinh** [comment]
@Zeleni9 
Do you make your predicted result in YOLO format?

**Comment by Zeleni9** [comment]
Thank you for fast response and great explanation, yea I currently writing it in YOLO format but in absolute values. I have pp4av in **ground truth:**

plate 401 728 490 752
plate 792 630 826 639

**and detections:**

face 0.5021612048149109 1154 584 1170 605
plate 0.3836093842983246 707 654 774 669
